Repository microsoft/onnxscript, pull requests merged in 2024-04, with the labels that each got.

#1349 Simplify linked list design with a hash table
  onnxscript/ir/_core.py
  onnxscript/ir/_linked_list.py
  onnxscript/ir/_linked_list_test.py
Labels: topic: IR

#1344 [IR] Mutable IR implementation
  onnxscript/ir/__init__.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_display.py
  onnxscript/ir/_display_test.py
  onnxscript/ir/_enums.py
  onnxscript/ir/_graph_comparison.py
  onnxscript/ir/_invariants.py
  onnxscript/ir/_linked_list.py
  onnxscript/ir/_linked_list_test.py
  onnxscript/ir/_metadata.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/convenience.py
  onnxscript/ir/serde.py
Labels: topic: IR

#1350 [Rewriter] Move `nsys_profile.py` from onnxrewirter to onnxscript
  .gitignore
  onnxscript/rewriter/__init__.py
  tools/ort_rewriter_profiling/README.md
  tools/ort_rewriter_profiling/bench_model.py
  tools/ort_rewriter_profiling/nsys_profile.py
  tools/ort_rewriter_profiling/ort_rewrite.py
  tools/ort_rewriter_profiling/profile_analysis.py
Labels: topic: rewriter

#1355 Fix test path for `test-experimental-torchlib-tracing`
  noxfile.py
  tests/function_libs/__init__.py
  tests/function_libs/torch_lib/__init__.py
Labels: topic: testing, merge at lgtm

#1356 Enable doctest in docstrings in CI
  onnxscript/_thirdparty/asciichartpy.py
  onnxscript/ir/_core.py
  pyproject.toml
Labels: topic: testing

#1364 [IR] Create GraphView for read-only view on a subgraph
  .gitignore
  onnxscript/ir/__init__.py
  onnxscript/ir/_core.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
  testdata/e2e_models/torchscript_model/torchscript_model.onnx
  tests/ir/graph_view_test.py
  tests/optimizer/test_models.py
Labels: topic: IR

#1368 [IR] Implement eq for Shape
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
Labels: merge at lgtm, topic: IR

#1367 Support pattern rewriting with parameters
  examples/pattern_rewriting.py
  onnxscript/_legacy_ir/__init__.py
  onnxscript/_legacy_ir/protobuilder.py
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/generic_pattern_test.py
Labels: topic: rewriter

#1373 Fix implementation of index with boolean indices | fix(torchlib)
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/extra_opinfo.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: topic: torch_lib

#1390 Implement `aten::diagonal_copy` | feat(torchlib)
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: topic: torch_lib

#1391 Bump required ONNX to 1.16
  .gitignore
  noxfile.py
  onnxscript/function_libs/torch_lib/ops/core.py
  pyproject.toml
Labels: topic: api

#1392 [IR] Rename apis
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
Labels: merge at lgtm, topic: IR

#1376 [IR] Improve repr and test; profile serde tests; test with py312
  .github/workflows/main.yaml
  .gitignore
  noxfile.py
  onnxscript/ir/_core.py
  requirements-dev.txt
  tests/ir/serde_test.py
Labels: topic: ci, topic: testing, topic: IR

#1369 [Rewriter] Integrate ONNX IR with rewriter pattern match
  examples/pattern_rewriting.py
  onnxscript/_legacy_ir/protobuilder_test.py
  onnxscript/_legacy_ir/visitor.py
  onnxscript/ir/_ir_utils_temp.py
  onnxscript/optimizer/__init__.py
  onnxscript/rewriter/__init__.py
  onnxscript/rewriter/_tape.py
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/broadcast_to_matmul_test.py
  onnxscript/rewriter/cast_constant_of_shape.py
  onnxscript/rewriter/cast_constant_of_shape_test.py
  onnxscript/rewriter/function_rule.py
  onnxscript/rewriter/gemm_to_matmul_add_test.py
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/generic_pattern_test.py
  onnxscript/rewriter/no_op_test.py
  onnxscript/rewriter/onnxruntime/__init__.py
  onnxscript/rewriter/onnxruntime/group_normalization_merge_silu_test.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization_test.py
  onnxscript/rewriter/onnxruntime/softmax.py
  onnxscript/rewriter/onnxruntime/softmax_test.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: topic: rewriter

#1394 Revert "Revert "[IR] Improve repr and test; profile serde tests; test with py312""
  .github/workflows/main.yaml
  .gitignore
  noxfile.py
  onnxscript/ir/_core.py
  requirements-dev.txt
  tests/ir/serde_test.py
Labels: topic: ci, topic: IR

#1380 [IR] Include metadata props in deserialization
  onnxscript/ir/_core.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
Labels: topic: IR

#1398 [IR] Improve APIs 3/n
  onnxscript/ir/__init__.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_enums.py
  onnxscript/ir/_enums_test.py
  onnxscript/ir/_metadata.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
  tests/ir/serde_test.py
Labels: topic: IR

#1399 [IR] Improve shape handling
  onnxscript/ir/__init__.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
Labels: topic: IR

#1400 [Function-Rewriter] Support BiasSplitGelu operator in `stable_diffusion_unet`
  .lintrunner.toml
  onnxscript/rewriter/onnxruntime/transformers/__init__.py
  onnxscript/rewriter/onnxruntime/transformers/biassplitgelu.py
  onnxscript/rewriter/onnxruntime/transformers/biassplitgelu_test.py
  onnxscript/values.py
  testdata/unittest_models/geglu_stable_diffusion_unet_0/geglu_stable_diffusion_unet_0.onnx
  testdata/unittest_models/geglu_stable_diffusion_unet_0/test_data_set_0/input_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_0/test_data_set_0/input_1.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_0/test_data_set_0/input_2.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_0/test_data_set_0/output_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_1/geglu_stable_diffusion_unet_1.onnx
  testdata/unittest_models/geglu_stable_diffusion_unet_1/test_data_set_0/input_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_1/test_data_set_0/input_1.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_1/test_data_set_0/input_2.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_1/test_data_set_0/output_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_2/geglu_stable_diffusion_unet_2.onnx
  testdata/unittest_models/geglu_stable_diffusion_unet_2/test_data_set_0/input_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_2/test_data_set_0/input_1.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_2/test_data_set_0/input_2.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_2/test_data_set_0/output_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_3/geglu_stable_diffusion_unet_3.onnx
  testdata/unittest_models/geglu_stable_diffusion_unet_3/test_data_set_0/input_0.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_3/test_data_set_0/input_1.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_3/test_data_set_0/input_2.pb
  testdata/unittest_models/geglu_stable_diffusion_unet_3/test_data_set_0/output_0.pb
  tools/function_rewriter_testing/function_unittest_producer.py
  tools/ort_rewriter_profiling/README.md
Labels: topic: rewriter

#1405 [IR] Avoid creating empty dictionaries during deserialization
  onnxscript/ir/serde.py
Labels: topic: IR

#1354 Use the new IR for building graphs in torchlib
  .github/workflows/main.yaml
  noxfile.py
  onnxscript/_internal/runtime_typing.py
  onnxscript/function_libs/torch_lib/_flags.py
  onnxscript/function_libs/torch_lib/graph_building/__init__.py
  onnxscript/function_libs/torch_lib/graph_building/_graph_building_ir.py
  onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py
  onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py
  onnxscript/ir/_naming_authority.py
  tests/function_libs/torch_lib/ops_test_common.py
Labels: topic: torch_lib, topic: IR

#1406 [IR] Remove the incorrect `_naming_authority.py`
  onnxscript/ir/_naming_authority.py
Labels: merge at lgtm, topic: IR

#1395 Integrate new IR with rewriter
  .lintrunner.toml
  examples/pattern_rewriting.py
  onnxscript/_legacy_ir/__init__.py
  onnxscript/_legacy_ir/irbuilder.py
  onnxscript/_legacy_ir/irbuilder_test.py
  onnxscript/_legacy_ir/protobuilder.py
  onnxscript/_legacy_ir/protobuilder_test.py
  onnxscript/_legacy_ir/visitor.py
  onnxscript/ir/_core.py
  onnxscript/optimizer/__init__.py
  onnxscript/rewriter/__init__.py
  onnxscript/rewriter/_ir_utils.py
  onnxscript/rewriter/_tape.py
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/broadcast_to_matmul_test.py
  onnxscript/rewriter/cast_constant_of_shape.py
  onnxscript/rewriter/cast_constant_of_shape_test.py
  onnxscript/rewriter/function_rule.py
  onnxscript/rewriter/gemm_to_matmul_add_test.py
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/generic_pattern_test.py
  onnxscript/rewriter/no_op_test.py
  onnxscript/rewriter/onnxruntime/__init__.py
  onnxscript/rewriter/onnxruntime/group_normalization_merge_silu_test.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization_test.py
  onnxscript/rewriter/onnxruntime/softmax.py
  onnxscript/rewriter/onnxruntime/softmax_test.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: merge at lgtm, topic: IR, topic: rewriter

#1414 [IR] Implement replace_all_uses_with
  onnxscript/ir/_convenience.py
  onnxscript/ir/convenience.py
  onnxscript/rewriter/pattern.py
Labels: topic: IR, topic: rewriter

#1417 [IR] Implement `convert_attributes`
  onnxscript/ir/_convenience.py
  onnxscript/ir/_core.py
  onnxscript/ir/serde.py
  onnxscript/rewriter/_tape.py
Labels: topic: IR

#1415 [IR] Add a safe option to graph.remove
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/rewriter/pattern.py
Labels: topic: IR, topic: rewriter

#1418 Use new IR in function rewriter
  .lintrunner.toml
  onnxscript/rewriter/__init__.py
  onnxscript/rewriter/function_rule.py
  onnxscript/rewriter/onnxruntime/transformers/biassplitgelu.py
  onnxscript/rewriter/onnxruntime/transformers/fastgelu.py
  onnxscript/rewriter/onnxruntime/transformers/layernorm.py
  onnxscript/rewriter/onnxruntime/transformers/multihead_attention.py
Labels: topic: IR, topic: rewriter

#1421 Skip test for `aten::mm` when input is sized 0
  tests/function_libs/torch_lib/ops_test_data.py
Labels: topic: torch_lib, topic: testing

#1437 [IR] Create readme
  onnxscript/ir/README.md
  onnxscript/ir/_linked_list.py
Labels: documentation, topic: IR

#1422 [IR] Rename Value.consumers() to Value.uses()
  onnxscript/ir/_convenience.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_protocols.py
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/pattern.py
Labels: topic: IR

#1411 Refactor pattern matcher
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/cast_constant_of_shape.py
  onnxscript/rewriter/erfgelu.py
  onnxscript/rewriter/gemm_to_matmul_add.py
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/generic_pattern_test.py
  onnxscript/rewriter/no_op.py
  onnxscript/rewriter/onnxruntime/group_normalization_merge_silu.py
  onnxscript/rewriter/onnxruntime/group_normalization_merge_silu_test.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py
  onnxscript/rewriter/onnxruntime/softmax.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: topic: rewriter

#1445 [IR] Update README.md
  onnxscript/ir/README.md
Labels: topic: IR

#1451 Update function opset imports in rewriter
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: topic: rewriter

#1461 Fix opset import test in pattern_test.py
  onnxscript/rewriter/pattern_test.py
Labels: merge at lgtm, topic: rewriter

#1317 Add unit test with dort and llama
  tests/test_dort.py
Labels: topic: torch_lib

#1469 Remove `-v` in CI tests to produce shorter logs
  .github/workflows/main.yaml
Labels: topic: ci, merge at lgtm

#1465 Add one test failing for the optimizer after a model optimized and inlined
  testdata/dort_models/llama_forward.onnx
  tests/optimizer/test_models.py
Labels: topic: testing, merge at lgtm

#1472 Turn shape type inference strict mode to false in optimizer
  onnxscript/optimizer/__init__.py
Labels: topic: rewriter

#1454 Rewrite stable diffusion unet with com.microsoft attenion operators
  onnxscript/rewriter/onnxruntime/transformers/__init__.py
  onnxscript/rewriter/onnxruntime/transformers/multihead_attention.py
  onnxscript/rewriter/onnxruntime/transformers/multihead_attention_test.py
  testdata/unittest_models/attn_stable_diffusion_unet_0/attn_stable_diffusion_unet_0.onnx
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_1.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_2.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_3.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_4.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_5.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/input_6.pb
  testdata/unittest_models/attn_stable_diffusion_unet_0/test_data_set_0/output_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/attn_stable_diffusion_unet_1.onnx
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_1.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_2.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_3.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_4.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_5.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/input_6.pb
  testdata/unittest_models/attn_stable_diffusion_unet_1/test_data_set_0/output_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/attn_stable_diffusion_unet_without_encoder_hidden_states_0.onnx
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/input_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/input_1.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/input_2.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/input_3.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/input_4.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/input_5.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_0/test_data_set_0/output_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/attn_stable_diffusion_unet_without_encoder_hidden_states_1.onnx
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/input_0.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/input_1.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/input_2.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/input_3.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/input_4.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/input_5.pb
  testdata/unittest_models/attn_stable_diffusion_unet_without_encoder_hidden_states_1/test_data_set_0/output_0.pb
Labels: topic: rewriter

#1483 Add device to TorchScriptTensor
  onnxscript/function_libs/torch_lib/graph_building/_graph_building_ir.py
  onnxscript/function_libs/torch_lib/graph_building/_graph_building_torch.py
  onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py
Labels: topic: graph transform
