Repository microsoft/onnxscript, pull requests merged in 2024-12, with the labels that each got.

#1971 [torchlib] torch.where(x) - default overload - is actually not implemented
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: topic: torch_lib

#1987 Extend onnx to script converter
  onnxscript/backend/onnx_export.py
  tools/onnx2external.py
  tools/onnx2script.py
Labels: topic: ast converter

#1951 [IR] Add torch tensor support for `ir.tensor`
  onnxscript/ir/_convenience.py
  onnxscript/ir/_convenience_test.py
  onnxscript/ir/tensor_adapters.py
Labels: topic: IR

#1992 [IR] Improve from_proto/to_proto typing with overloads
  docs/intermediate_representation/getting_started.ipynb
  onnxscript/ir/serde.py
Labels: topic: IR
