Repository microsoft/onnxscript, pull requests merged in 2024-05, with the labels that each got.

#1486 Clean up CI testing failures
  onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: broken ci

#1489 [IR] Test IR roundtrip with model zoo
  tools/ir/model_zoo_test/model_zoo_test.py
Labels: topic: testing, topic: IR

#1482 [optimizer][docs] Add Tutorial for Optimizer API
  docs/conf.py
  docs/index.md
  docs/optimizer/index.md
  docs/optimizer/optimize.md
  docs/rewriter/rewrite_patterns.md
  onnxscript/optimizer/__init__.py
  onnxscript/optimizer/constant_folding.py
  onnxscript/optimizer/copy_propagation.py
  onnxscript/optimizer/copy_propagation_test.py
  onnxscript/optimizer/simple_function_folding.py
Labels: documentation, topic: optimizer

#1493 [docs] Reorder tutorials to have a common landing page
  docs/index.md
  docs/test/test_documentation_examples.py
  docs/tutorial/index.md
  docs/tutorial/optimizer/index.md
  docs/tutorial/optimizer/optimize.md
  docs/tutorial/rewriter/examples/broadcast_matmul.py
  docs/tutorial/rewriter/examples/erfgelu.py
  docs/tutorial/rewriter/examples/img/broadcast_01.png
  docs/tutorial/rewriter/examples/img/broadcast_02.png
  docs/tutorial/rewriter/examples/img/erfgelu_01.png
  docs/tutorial/rewriter/examples/img/erfgelu_02.png
  docs/tutorial/rewriter/examples/img/erfgelu_03_commute.png
  docs/tutorial/rewriter/examples/img/erfgelu_04_commute.png
  docs/tutorial/rewriter/examples/img/erfgelu_05_commute.png
  docs/tutorial/rewriter/examples/img/erfgelu_06_commute.png
  docs/tutorial/rewriter/examples/img/erfgelu_07_commute.png
  docs/tutorial/rewriter/index.md
  docs/tutorial/rewriter/rewrite_patterns.md
Labels: documentation

#1495 Unify the two pattern-matchers
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/generic_pattern_test.py
  onnxscript/rewriter/pattern.py
Labels: topic: rewriter

#1497 [docs] Fix math rendering
  docs/conf.py
  docs/tutorial/rewriter/rewrite_patterns.md
Labels: documentation, merge at lgtm

#1496 Update dev instructions on README; Fix math rendering
  README.md
  docs/conf.py
  docs/tutorial/rewriter/rewrite_patterns.md
Labels: documentation

#1441 [IR] Allow tensor created with numpy unsupported dtypes
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_display_test.py
  onnxscript/ir/_enums.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/_type_casting.py
  onnxscript/ir/_type_casting_test.py
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
  tests/ir/serde_roundtrip_test.py
Labels: topic: IR

#1481 [IR] Create documentation for tensors
  docs/conf.py
  docs/intermediate_representation/index.md
  docs/intermediate_representation/tensors.md
  onnxscript/ir/__init__.py
  requirements-dev.txt
Labels: documentation, topic: IR

#1492 Add bfloat16 to float16 converter in onnxruntime specific rewriter
  onnxscript/rewriter/onnxruntime/__init__.py
  onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter.py
  onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter_test.py
Labels: topic: rewriter

#1507 [IR] Support specifying output values in Node init
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
Labels: topic: IR

#1509 [IR] Support deserializing unsorted graphs
  onnxscript/ir/_core.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
Labels: merge at lgtm, topic: IR

#1513 Add provider argument to bfloat16 converter test
  onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter_test.py
Labels: merge at lgtm, topic: rewriter

#1512 Fix bugs in matmul condition function and rename tests
  docs/tutorial/rewriter/examples/broadcast_matmul.py
  docs/tutorial/rewriter/rewrite_patterns.md
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/gemm_to_matmul_add.py
  onnxscript/rewriter/gemm_to_matmul_add_test.py
Labels: topic: rewriter

#1510 [IR] INT4 support in external tensors
  docs/intermediate_representation/tensors.md
  noxfile.py
  onnxscript/_internal/version_utils.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
  requirements-dev.txt
Labels: topic: IR

#1516 [IR] Implement `node` and `num_nodes` on Graph
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
Labels: topic: IR

#1518 [build] Make the urls field dynamic
  pyproject.toml
Labels: merge at lgtm

#1508 [IR] Implement to_proto and from_proto convenience functions
  docs/conf.py
  docs/intermediate_representation/getting_started.ipynb
  docs/intermediate_representation/index.md
  onnxscript/ir/__init__.py
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
  requirements-dev.txt
Labels: topic: IR

#1515 Unify single-output and multi-output pattern matchers
  docs/tutorial/rewriter/examples/broadcast_matmul.py
  docs/tutorial/rewriter/examples/erfgelu.py
  docs/tutorial/rewriter/rewrite_patterns.md
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/cast_constant_of_shape.py
  onnxscript/rewriter/erfgelu.py
  onnxscript/rewriter/gemm_to_matmul_add.py
  onnxscript/rewriter/generic_pattern.py
  onnxscript/rewriter/generic_pattern_test.py
  onnxscript/rewriter/no_op.py
  onnxscript/rewriter/onnxruntime/group_normalization_merge_silu.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py
  onnxscript/rewriter/onnxruntime/softmax.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: topic: rewriter

#1532 Update CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: documentation, merge at lgtm

#1514 Contributed pixelshuffle op
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: topic: torch_lib, merge at lgtm

#1484 Handling bfloat16 constant propagation
  onnxscript/_legacy_ir/visitor.py
  onnxscript/optimizer/constant_folding.py
Labels: topic: optimizer

#1538 [fix ci] Disable macos tests for native_layer_norm_float32
  tests/function_libs/torch_lib/ops_test_common.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: broken ci

#1537 [IR] Improve name authority to generate unique names
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_name_authority.py
  onnxscript/ir/_name_authority_test.py
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
  onnxscript/rewriter/onnxruntime/bfloat16_utils/bfloat16_converter.py
Labels: topic: IR

#1546 Create a debug flag
  onnxscript/__init__.py
Labels: topic: api

#1528 [IR] Create pass infra
  onnxscript/ir/__init__.py
  onnxscript/ir/_invariants.py
  onnxscript/ir/passes/__init__.py
  onnxscript/ir/passes/_pass_infra.py
  onnxscript/optimizer/__init__.py
  onnxscript/optimizer/remove_unused_function.py
  onnxscript/optimizer/simple_function_folding_test.py
  onnxscript/rewriter/__init__.py
  onnxscript/rewriter/onnxruntime/__init__.py
Labels: merge at lgtm, topic: IR, topic: optimizer

#1542 [IR] Fix broadcast_to_matmul
  docs/tutorial/rewriter/examples/broadcast_matmul.py
  onnxscript/rewriter/_ir_utils.py
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/broadcast_to_matmul_test.py
Labels: topic: rewriter

#1561 Simplify get_numpy_from_ir_value
  onnxscript/rewriter/_ir_utils.py
  onnxscript/rewriter/onnxruntime/instance_to_group_normalization.py
  onnxscript/rewriter/onnxruntime/transformers/layernorm.py
  onnxscript/rewriter/onnxruntime/transformers/multihead_attention.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: topic: IR, topic: rewriter

#1567 Fix broadcast rule of expanding dims
  onnxscript/rewriter/broadcast_to_matmul.py
  onnxscript/rewriter/broadcast_to_matmul_test.py
Labels: topic: rewriter

#1549 [IR] Create `ir.tensor()` as a convenience Tensor initializer; use ml_dtypes to support int4/bfloat16
  docs/intermediate_representation/tensors.md
  onnxscript/ir/__init__.py
  onnxscript/ir/_convenience.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_enums.py
  onnxscript/ir/_type_casting.py
  onnxscript/ir/_type_casting_test.py
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
  pyproject.toml
  requirements-dev.txt
Labels: topic: IR

#1565 Create a recursive graph iterator and use it to refactor UnusedFunctionRemover
  onnxscript/ir/__init__.py
  onnxscript/ir/passes/__init__.py
  onnxscript/ir/passes/_pass_infra.py
  onnxscript/ir/traversal.py
  onnxscript/ir/traversal_test.py
  onnxscript/optimizer/remove_unused_function.py
Labels: topic: IR, topic: rewriter

#1576 [IR] Make tensor types hashable
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
Labels: topic: IR
