Repository microsoft/onnxscript, pull requests merged in 2025-03, with the labels that each got.

#2061 [torchlib] Fix index_put: handle None cases
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/extra_opinfo.py
Labels: module: torchlib

#1547 Add unique op
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/extra_opinfo.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2094 Fix Op (Slice complex) | improve dim expression
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2098 [IR] Fix deserialize_node
  onnxscript/ir/serde.py
  onnxscript/ir/serde_test.py
Labels: module: IR

#2100 [torchlib] Fix layer norm dtype
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2104 Remove the experimental IR graph builder
  onnxscript/function_libs/torch_lib/_flags.py
  onnxscript/function_libs/torch_lib/graph_building/__init__.py
  onnxscript/function_libs/torch_lib/graph_building/_graph_building_ir.py
Labels: module: torchlib, topic: better engineering

#2103 [CI] Fix test errors on windows
  onnxscript/function_libs/torch_lib/graph_building/graph_building_test.py
  onnxscript/ir/_io_test.py
Labels: topic: ci

#2106 A couple of extensions to MHA fusion
  onnxscript/rewriter/ort_fusions/mha.py
Labels: module: rewriter

#2108 Fix Op (convolution) | add nd support to convolution
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/extra_opinfo.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2109 Turn constant folder and dce into passes
  onnxscript/optimizer/_constant_folding.py
  onnxscript/optimizer/_remove_unused.py
Labels: topic: graph transform, module: optimizer

#2117 [IR] Create a shape inference pass using onnx shape inference
  onnxscript/ir/_io.py
  onnxscript/ir/passes/_pass_infra.py
  onnxscript/ir/passes/common/shape_inference.py
  onnxscript/ir/passes/common/shape_inference_test.py
Labels: topic: passes

#2125 Fix DORT CI according to torch-nightly changes
  onnxscript/tools/training_helper.py
  onnxscript/tools/transformers_models/phi_test.py
Labels: topic: ci

#2124 [rewriter] Enable llama rule sets
  onnxscript/optimizer/_optimizer.py
  onnxscript/rewriter/_ir_utils.py
  onnxscript/rewriter/llama_rule_sets.py
  onnxscript/rewriter/llama_rule_sets_test.py
Labels: module: rewriter, module: optimizer

#2126 [IR] Convenience constructor for Node
  onnxscript/ir/__init__.py
  onnxscript/ir/_convenience/__init__.py
  onnxscript/ir/_convenience/_constructors.py
  onnxscript/ir/_convenience/_constructors_test.py
  onnxscript/ir/convenience.py
Labels: module: IR

#2123 Add spda rules and tests for unmasked patterns
  onnxscript/rewriter/ort_fusions/sdpa.py
  onnxscript/rewriter/ort_fusions/sdpa_test.py
Labels: module: rewriter

#2135 Use self._use_mask in sdpa rewrite call
  onnxscript/rewriter/ort_fusions/sdpa.py
  onnxscript/rewriter/ort_fusions/sdpa_test.py
Labels: module: rewriter

#2134 [rewriter | torchlib] respect ops order in torchscript graph
  onnxscript/function_libs/torch_lib/ops/nn.py
  onnxscript/rewriter/ort_fusions/gelu.py
  onnxscript/rewriter/ort_fusions/gelu_test.py
Labels: module: torchlib, module: rewriter

#2120 [IR] Improve pass infra
  onnxscript/ir/passes/__init__.py
  onnxscript/ir/passes/_pass_infra.py
  onnxscript/ir/passes/common/shape_inference.py
  onnxscript/optimizer/_constant_folding.py
  onnxscript/optimizer/_remove_unused.py
  onnxscript/optimizer/_remove_unused_function.py
Labels: module: IR, topic: passes

#2143 [Passes] Consolidate DCE passes into common passes
  onnxscript/ir/passes/_pass_infra.py
  onnxscript/ir/passes/common/unused_removal.py
  onnxscript/ir/passes/common/unused_removal_test.py
  onnxscript/optimizer/__init__.py
  onnxscript/optimizer/_legacy/_optimizer.py
  onnxscript/optimizer/_legacy/_simple_function_folding_test.py
  onnxscript/optimizer/_optimizer.py
  onnxscript/optimizer/_remove_unused.py
  onnxscript/optimizer/_remove_unused_function.py
  onnxscript/rewriter/__init__.py
  onnxscript/tools/benchmark/benchmark_helpers.py
Labels: module: optimizer, topic: passes

#2138 Make the return type of rewrite check functions a MatchResult object
  onnxscript/rewriter/llama_rule_sets.py
  onnxscript/rewriter/ort_fusions/cos_sin_cache.py
  onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py
  onnxscript/rewriter/ort_fusions/gqa.py
  onnxscript/rewriter/ort_fusions/mha.py
  onnxscript/rewriter/ort_fusions/rms_normalization.py
  onnxscript/rewriter/ort_fusions/rotary_embedding.py
  onnxscript/rewriter/ort_fusions/sdpa.py
  onnxscript/rewriter/ort_fusions/sdpa_test.py
  onnxscript/rewriter/pattern.py
Labels: topic: breaking changes, module: rewriter

#2150 Optimize away zero-length concat operands
  onnxscript/optimizer/_constant_folding.py
  onnxscript/optimizer/_constant_folding_test.py
Labels: module: optimizer

#2090 Fix include_self for scatter_reduce
  onnxscript/function_libs/torch_lib/ops/core.py
  onnxscript/optimizer/_constant_folding.py
  tests/function_libs/torch_lib/e2e_ops_tests.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2147 [torchlib] Fix aten_div rounding_mode
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/ops_test_common.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib
