Repository microsoft/onnxscript, pull requests merged in 2025-02, with the labels that each got.

#2049 [torchlib] Add memory_format to ones_like
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2048 Fix aten_pow when first input is a python constant
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2050 [torchlib] Fix various implementations
  noxfile.py
  onnxscript/function_libs/torch_lib/ops/core.py
  onnxscript/function_libs/torch_lib/ops/fft.py
  onnxscript/function_libs/torch_lib/ops/linalg.py
  onnxscript/function_libs/torch_lib/ops/nn.py
  onnxscript/function_libs/torch_lib/ops/prims.py
  onnxscript/function_libs/torch_lib/ops/special.py
  onnxscript/function_libs/torch_lib/registration.py
  tests/function_libs/torch_lib/extra_opinfo.py
  tests/function_libs/torch_lib/ops_test.py
  tests/function_libs/torch_lib/ops_test_common.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2053 Expose opset22
  onnxscript/__init__.py
Labels: topic: api

#2039 Refactor ort specific fusions
  onnxscript/rewriter/__init__.py
  onnxscript/rewriter/function_rule.py
  onnxscript/rewriter/onnxruntime/README.md
  onnxscript/rewriter/onnxruntime/__init__.py
  onnxscript/rewriter/onnxruntime/transformers/__init__.py
  onnxscript/rewriter/onnxruntime/transformers/biassplitgelu.py
  onnxscript/rewriter/onnxruntime/transformers/biassplitgelu_test.py
  onnxscript/rewriter/onnxruntime/transformers/fastgelu.py
  onnxscript/rewriter/onnxruntime/transformers/fastgelu_test.py
  onnxscript/rewriter/onnxruntime/transformers/layernorm.py
  onnxscript/rewriter/onnxruntime/transformers/layernorm_test.py
  onnxscript/rewriter/onnxruntime/transformers/multihead_attention.py
  onnxscript/rewriter/onnxruntime/transformers/multihead_attention_test.py
  onnxscript/rewriter/ort_fusions/__init__.py
  onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py
  onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets_test.py
  onnxscript/rewriter/ort_fusions/group_normalization_merge_silu.py
  onnxscript/rewriter/ort_fusions/group_normalization_merge_silu_test.py
  onnxscript/rewriter/ort_fusions/instance_to_group_normalization.py
  onnxscript/rewriter/ort_fusions/instance_to_group_normalization_test.py
  onnxscript/rewriter/ort_fusions/rotary_embedding.py
  onnxscript/rewriter/ort_fusions/softmax.py
  onnxscript/rewriter/ort_fusions/softmax_test.py
  onnxscript/tools/benchmark/benchmark_helpers.py
Labels: topic: better engineering

#2055 [torchlib] Make matmul trace_only
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2057 [torchlib] Simplify aten_trunc implementation
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2059 Bump version to 0.3.0
  VERSION
Labels: topic: release

#2046 Fix misleading annotation in the documentation
  docs/conf.py
  onnxscript/optimizer/__init__.py
  onnxscript/tools/benchmark/benchmark_helpers.py
  onnxscript/tools/transformers_models/__init__.py
Labels: topic: documentation

#2066 [torchlib] Implement clamp* scalar overloads
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2065 Enable extraction of rewritten subgraph as model-local function
  onnxscript/optimizer/__init__.py
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: module: rewriter

#2068 [torchlib] Trace several ops
  onnxscript/function_libs/torch_lib/ops/core.py
  onnxscript/function_libs/torch_lib/ops/nn.py
Labels: module: torchlib

#2069 [torchlib] Update operator:pow implementation
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2070 Fix Op(unflatten)
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2071 Make onnxscript release 1ES compliant
  .azure-pipelines/_release-template.yml
  .azure-pipelines/release-dev.yml
  .azure-pipelines/release.yml
  .azure-pipelines/stages/jobs/steps/release-steps.yml
  .azure-pipelines/stages/release-stage.yml
Labels: topic: build

#2077 Add a couple of variants of patterns in ORT fusions
  onnxscript/rewriter/ort_fusions/_core.py
  onnxscript/rewriter/ort_fusions/cos_sin_cache.py
  onnxscript/rewriter/ort_fusions/sdpa.py
  onnxscript/rewriter/pattern.py
Labels: module: rewriter

#2078 [IR] Fix an error when checking for float8_e4m3fnuz type in ir.Tensor
  onnxscript/ir/_core.py
Labels: module: IR
