Repository microsoft/onnxscript, pull requests merged in 2025-05, with the labels that each got.

#2242 Add support for a non-backtracking version of pattern disjunction
  docs/api/rewriter_pattern.md
  onnxscript/rewriter/pattern.py
  onnxscript/rewriter/pattern_test.py
Labels: module: rewriter

#2248 [IR] Display constant tensors for Value
  onnxscript/ir/_convenience/__init__.py
  onnxscript/ir/_core.py
  onnxscript/ir/serde.py
Labels: topic: ux, module: IR

#2081 [IR] Refactor TensorBase to simplify implementation
  onnxscript/ir/_core.py
  onnxscript/ir/serde.py
Labels: module: IR

#2262 Create short tensor str for nodes
  onnxscript/ir/_core.py
Labels: topic: ux, module: IR

#2259 Rewrite Skip fusions with check functions
  onnxscript/rewriter/ort_fusions/skip_normalization.py
Labels: module: rewriter, topic: ort-fusions

#2266 [Pass] Support lifting subgraph initializers to main graph
  onnxscript/ir/passes/common/constant_manipulation.py
  onnxscript/ir/passes/common/constant_manipulation_test.py
  onnxscript/optimizer/_optimizer.py
Labels: topic: passes

#2253 Add add/remove initializers passes
  onnxscript/ir/passes/common/constant_manipulation.py
  onnxscript/ir/passes/common/constant_manipulation_test.py
Labels: topic: passes

#2221 Add fusion rules (Whisper optimizations)
  onnxscript/rewriter/ort_fusions/_core.py
  onnxscript/rewriter/ort_fusions/attention.py
  onnxscript/rewriter/ort_fusions/attention_test.py
  onnxscript/rewriter/ort_fusions/fuse_mha_bias.py
  onnxscript/rewriter/ort_fusions/fuse_xformers_test.py
  onnxscript/rewriter/ort_fusions/mha.py
  onnxscript/rewriter/ort_fusions/mha_test.py
  onnxscript/rewriter/ort_fusions/models/_whisper_decoder.py
  onnxscript/rewriter/ort_fusions/models/_whisper_encoder.py
  onnxscript/rewriter/ort_fusions/sdpa.py
  onnxscript/rewriter/ort_fusions/skip_normalization_test.py
Labels: topic: graph transform, module: rewriter, topic: ort-fusions

#2286 Temporarily skip the whisper test in skip layernorm fusion
  onnxscript/rewriter/ort_fusions/skip_normalization_test.py
Labels: merge at lgtm

#2287 [torchlib] Fix scatter reduce on error cases
  onnxscript/function_libs/torch_lib/ops/core.py
Labels: module: torchlib

#2282 [IR] Record owning graph for input/output/initializers
  onnxscript/ir/_convenience/__init__.py
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/ir/_graph_containers.py
  onnxscript/ir/external_data_test.py
  onnxscript/ir/passes/common/clear_metadata_and_docstring_test.py
  onnxscript/ir/passes/common/constant_manipulation.py
  onnxscript/ir/passes/common/constant_manipulation_test.py
  onnxscript/optimizer/_constant_folding.py
Labels: enhancement, merge at lgtm, module: IR

#2283 [IR] Normalize "ai.onnx" domain to ""
  onnxscript/ir/_core.py
  onnxscript/ir/_core_test.py
  onnxscript/optimizer/_constant_folding.py
  onnxscript/version_converter/_version_converter.py
Labels: module: IR

#2291 Add from_onnx_text function to convert ONNX text to IR model
  docs/ir/ir_api/core.md
  onnxscript/ir/__init__.py
  onnxscript/ir/passes/common/inliner_test.py
  onnxscript/ir/serde.py
  onnxscript/optimizer/_constant_folding_test.py
  onnxscript/rewriter/no_op_test.py
  onnxscript/version_converter/_version_converter_test.py
Labels: topic: api, module: IR

#2297 [IR] Docs for Node
  onnxscript/ir/_core.py
Labels: topic: documentation, module: IR

#2288 Unify rule implementations with classes
  docs/api/rewriter_pattern.md
  onnxscript/rewriter/llama_rule_sets.py
  onnxscript/rewriter/ort_fusions/fused_matmul_rule_sets.py
  onnxscript/rewriter/pattern.py
Labels: merge at lgtm, module: rewriter

#2307 [IR] introduce slice support on graph
  onnxscript/ir/_core.py
  onnxscript/ir/_linked_list.py
  onnxscript/ir/_linked_list_test.py
Labels: topic: api, module: IR

#2328 Remove the RefAttr class
  onnxscript/ir/_convenience/__init__.py
  onnxscript/ir/_convenience/_constructors.py
  onnxscript/ir/_core.py
  onnxscript/ir/_protocols.py
  onnxscript/ir/_tape.py
  onnxscript/ir/external_data.py
  onnxscript/ir/passes/common/inliner.py
  onnxscript/ir/serde.py
  onnxscript/optimizer/_constant_folding.py
  onnxscript/rewriter/_pattern_ir.py
  onnxscript/rewriter/_rewrite_rule.py
  onnxscript/rewriter/llama_rule_sets.py
  onnxscript/version_converter/_version_converter.py
Labels: topic: api, topic: breaking changes, module: IR

#2332 Fix handling of attention-bias in MHA fusion
  onnxscript/rewriter/ort_fusions/mha.py
Labels: module: rewriter

#2333 Update publish as a deployment job
  .azure-pipelines/publish.yml
Labels: merge at lgtm, topic: release

#2340 [torchlib] Update linear implementation to support 1d weights
  onnxscript/function_libs/torch_lib/ops/nn.py
Labels: module: torchlib, merge at lgtm

#2338 [IR][fix] Implement copy() for graph inputs/outputs
  onnxscript/ir/_core_test.py
  onnxscript/ir/_graph_containers.py
Labels: merge at lgtm, module: IR

#2312 Rewriter: Fold Batchnorm nodes
  onnxscript/rewriter/fuse_batchnorm.py
  onnxscript/rewriter/fuse_batchnorm_test.py
Labels: module: rewriter

#2347 [IR] Handle external initializers in subgraphs
  onnxscript/ir/external_data.py
Labels: topic: breaking changes, module: IR

#2346 [torchlib] Set allowzero=True on Reshape where appropriate
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib, merge at lgtm

#2353 Implement `__repr__` for MatchResult
  onnxscript/rewriter/_basics.py
Labels: module: rewriter
