Repository microsoft/onnxscript, pull requests merged in 2025-10, with the labels that each got.

#2591 Remove usages of ir.Input in test
  onnxscript/rewriter/rules/common/_fuse_conv_affine_test.py
Labels: topic: better engineering

#2592 Improve aten_floor_divide for int inputs
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/extra_opinfo.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib

#2594 Expose the should_fold option to optimize()
  onnxscript/optimizer/_optimizer.py
Labels: topic: api, module: optimizer

#2599 Update torch api error message to include value names
  onnxscript/_framework_apis/torch_2_5.py
Labels: topic: api

#2613 support for scalar args to aten::scatter
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/extra_opinfo.py
Labels: module: torchlib

#2597 Simplify aten_unbind when shape is static
  onnxscript/function_libs/torch_lib/ops/core.py
  tests/function_libs/torch_lib/ops_test.py
  tests/function_libs/torch_lib/ops_test_data.py
Labels: module: torchlib, merge at lgtm
